#!/usr/bin/env python

import argparse
import re


from unifi.controller import Controller

parser = argparse.ArgumentParser()
parser.add_argument('-c', '--controller', default='unifi', help='the controller address (default "unifi")')
parser.add_argument('-u', '--username', default='admin', help='the controller usernane (default("admin")')
parser.add_argument('-p', '--password', default='', help='the controller password')
parser.add_argument('-v', '--version', default='v2', help='the controller base version (default "v2")')
parser.add_argument('-s', '--siteid', default='default', help='the site ID, UniFi >=3.x only (default "default")')
parser.add_argument('-m', '--mac', default='00:00:00:00:00:00', help='the mac address to check (default "00:00:00:00:00:00")')
args = parser.parse_args()

c = Controller(args.controller, args.username, args.password, args.version, args.siteid)

new_mac = re.sub("-",":",args.mac)
clients = c.get_clients()
client = dict([("ip",mac['ip']) for mac in clients if mac['mac']==new_mac.lower()])
ip = client.get('ip')

print '{}'.format(ip)


